services:
  task_db:
    image: mongo
    container_name: task_db
    env_file: ./.env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./data_mongodb:/data/db
      - ./data_mongodb/log:/var/log/mongodb/
    ports:
      - $MONGO_LOCAL_PORT:$MONGO_DOCKER_PORT